
export const leftJoinData = [
  {
    uid: 1,
    name: 'user1',
    real_name: 'rn1',
    // ctime: { },
    age: 10,
    address: 'address1',
    order_id: '1',
    order_name: 'order1',
    tb_user_ext_uid: 1,
    tb_order_uid: 1,
    // tb_order_ctime: { },
  },
  {
    uid: 1,
    name: 'user1',
    real_name: 'rn1',
    // ctime: { },
    age: 10,
    address: 'address1',
    order_id: '2',
    order_name: 'order2',
    tb_user_ext_uid: 1,
    tb_order_uid: 1,
    // tb_order_ctime: { },
  },
  {
    uid: 2,
    name: 'user2',
    real_name: 'rn2',
    // ctime: { },
    age: 10,
    address: 'address1',
    order_id: null,
    order_name: null,
    tb_user_ext_uid: 2,
    tb_order_uid: null,
    tb_order_ctime: null,
  },
  {
    uid: 3,
    name: 'user3',
    real_name: 'rn3',
    // ctime: ,
    age: null,
    address: null,
    order_id: null,
    order_name: null,
    tb_user_ext_uid: null,
    tb_order_uid: null,
    tb_order_ctime: null,
  },
]
