# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: manual-publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Leave empty or input major|minor|patch'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14-buster

    strategy:
      matrix:
        node: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: npm build
        run: |
          openssl version
          node -v
          npm i -g lerna
          npm run bootstrap
          npm run build --if-present
      - name: npm ci
        run: |
          # lint must after build
          lerna run lint:nofix
          npm run ci
        env:
          CI: true

      - name: npm publish
        run: |
          git config --global user.name 'github-actions[bot]'
          # npm run pub major
          bash .scripts/publish.sh --conventional-commits --create-release github ${{ github.event.inputs.semver }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_ci_test
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
